### ISSUE TITLE
MobileSafariClickEventPlugin requires touch events to be initialized

### ISSUE THREAD

**Issue by Simek** [facebook/react#1169]
Event do not trigger when node do not have "cursor: pointer" style on it.

Here you have an example:
http://jsfiddle.net/kb3gN/1345/

**Comment by percyhanna** [comment]
As I noted in #2931, you need to set the `cursor` on a non-`:hover` pseudo-class selector, otherwise iOS doesn't register that it's clickable.

@MoOx I would think you might be able to do something like this:

```css
.my-clickable-thing {
  cursor: pointer;
}

.my-clickable-thing:hover {
  cursor: zoom;
}
```
