### ISSUE TITLE
css block semicolon bug

### ISSUE THREAD

**Issue by phanirithvij** [facebook/react#15429]
**BUG**

**Importance** : Low (It wasted my time :sob:)

*tags* : css

**Current behavior**

Using `react-scripts start`, `create-react-app` and all defaults,

When a css code block ends with a semicolon
for eg:
here
> .play{...} `;`

File: `src/components/Player.css`

```css
.play {
    ...
} ; /* <-- this semicolon */

/* all rules after this point become dead code */

.btn-disabled {
    color: rgb(255, 21, 21);
    background: blue;
}
...
```
When the file is imported in a `src/components/Player.tsx` using `import "./Player.css"`

The browser doesn't display the css rules after the semicolon.
i.e. the rules starting from `btn-disabled` are not being sent to the client side.
only the `.play` is applied.
i.e. It's ending the css parsing the moment it sees a semicolon(?)

But when the semicolon after `play` class is removed in the css declarations and it's changed to

```css
.play{
    ...
} /* no semicolon */

.btn-disabled {
    color: rgb(255, 21, 21);
    background: blue;
}
...
```
Then the browser component has the classes applied and has its default behavior.

**Expected behavior**
The scoped css is supposed to work even with a semicolon.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Latest `16.8.6`

**Steps to reproduce**
As code sandbox conveniently uses react and in [https://codesandbox.io/s/m8n3jrlwj](https://codesandbox.io/s/m8n3jrlwj) add a semicolon in line 3 in `styles.css`
Make it
```css
.app {
  background: red;
} ;
```
from
```css
.app {
  background: red;
}
```

**Doubts**
- Is it wrong to add a semicolon at the end after a css code block?
- I couldn't find it in w3 standards.
