### ISSUE TITLE
Bug: It seems that the concurrent mode does not work as expect

### ISSUE THREAD

**Issue by lizuncong** [facebook/react#25263]
React version: 17.0.1

## Steps To Reproduce

Here I use a while loop to simulate a long task.When I click on the div, the animation stops

```jsx
import React from "react";
import ReactDOM from "react-dom";

const NumberComp = ({ count }) => {
  const start = new Date().getTime();
// Simulate time-consuming tasks
  while (new Date().getTime() - start < 1) {}
  return count;
};
const arr = [];
for (let i = 0; i < 1000; i++) {
  arr.push(i);
}
class Home extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      count: 0,
    };
  }

  render() {
    return (
      <>
        <div
          onClick={() => this.setState({ count: this.state.count + 1 })}
          className="animation"
        >{`count：${this.state.count}`}</div>
        {arr.map((i) => (
          <NumberComp key={i} count={i} />
        ))}
      </>
    );
  }
}

ReactDOM.unstable_createRoot(document.getElementById("root")).render(<Home />);

```
the css
```css
.animation {
    display: block;
     width: 100px;
     height: 100px;
     background: lightyellow;
     animation: myfirst 5s;
     animation-iteration-count: infinite;
}
@keyframes myfirst {
   from {
        width: 30px;
        height: 30px;
        border-radius: 0;
  }
      to {
        width: 200px;
        height: 200px;
        border-radius: 50%;
      }
}
```

## The current behavior

When I click on the div, the animation stops.And the performance is as follows:

<img width="1434" alt="image" src="https://user-images.githubusercontent.com/14917591/190122954-78a155ea-75fb-4bb3-9181-2c00c326706b.png">

It seems that the concurrent mode does not work

## The expected behavior

Since it's concurrent mode, when I click on the div, the animation shouldn't stop and the page shouldn't freeze
