### ISSUE TITLE
Bug: Github pages not displaying my Vite.js app  

### ISSUE THREAD

**Issue by claudeMassaad** [facebook/react#25520]
Link to code example: https://github.com/claudeMassaad/TENZIES-GAME-REACT-APP

Here's my main and index.html in Vite app:

![Screen Shot 2022-10-20 at 10 16 31 AM](https://user-images.githubusercontent.com/109232112/196881586-b1023f1c-5173-4200-9395-6c346833aec7.png)
![Screen Shot 2022-10-20 at 10 16 45 AM](https://user-images.githubusercontent.com/109232112/196881627-064570e9-e384-40c1-a44a-6879da8eb0e2.png)

## The current behavior
![Screen Shot 2022-10-20 at 10 15 39 AM](https://user-images.githubusercontent.com/109232112/196881433-8e7d367b-4f93-406d-b262-88627627f5b7.png)

 Once i push to my github and then go to the pages feature on github where github generates a link for my web app, the screen is white and i get this error:Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/jsx". Strict MIME type checking is enforced for module scripts per HTML spec.
Now i cant change the name of main.jsx to main.js because Vite requires .jsx extensions.
Any help?

## The expected behavior

I am running a react app created with Vite.js locally and everything works perfectly when i run npm run dev. It should do the same when github generates a link for my website

**Comment by eps1lon** [comment]
Support requests filed as GitHub issues often go unanswered. We want you to find the answer you're looking for, so we suggest the following alternatives:

Coding Questions
If you have a coding question related to React and React DOM, it might be better suited for Stack Overflow. It's a great place to browse through frequent questions about using React, as well as ask for help with specific questions.

https://stackoverflow.com/questions/tagged/react

Talk to other React developers
There are many online forums which are a great place for discussion about best practices and application architecture as well as the future of React.

https://reactjs.org/community/support.html

**Comment by Tim-Mclennan** [comment]
Did you end up finding a solution to this? :)

**Comment by GuilhermeJackson** [comment]
I followed this step and it worked.
https://vitejs.dev/guide/static-deploy.html

**Comment by GRAviTY-GAGAN** [comment]
https://vitejs.dev/guide/static-deploy.html this is also not working for me.

**Comment by maik-emanoel** [comment]
https://vitejs.dev/guide/static-deploy.html I tried to follow these steps, but it also don't worked

**Comment by GRAviTY-GAGAN** [comment]
@maik-emanoel i was making a mistake there did you add a path to homepage in package.json file? If not try that it works i guess

**Comment by maik-emanoel** [comment]
@GRAviTY-GAGAN  Yeah, I tried to do that too, but don't worked

**Comment by GRAviTY-GAGAN** [comment]
Hoo great 👍🏻

**Comment by OwaisQasim** [comment]
instead of opening the react app with Live server, You need to open it with "npm run dev". It should work that way.

**Comment by GRAviTY-GAGAN** [comment]
The discussion is a deployment no problem with running the app

**Comment by MiguelCamilo** [comment]
> I followed this step and it worked.
> https://vitejs.dev/guide/static-deploy.html

This worked for me, going through the vite docs, they have docs for deploying with a majority of provider

**Comment by DavidCandelaRuz** [comment]
Trying to load page with Live Server (Ritwick Dey) and problem appear. 
I have never found the MIME problem but when I use on console `npm run dev` it was **solved** for me.

on console: `npm run dev`

**Comment by GRAviTY-GAGAN** [comment]
Yeah, it's not a simple HTML file right so it won't work with the live server if you are using vite react `npm run dev` if you created the project with NPX create-react-app then `npm start `(depends on what you write inside the script of package.json file)

**Comment by BasemYahia402** [comment]
https://vitejs.dev/guide/static-deploy.html This is also not working for me.

**Comment by DavidCandelaRuz** [comment]
> https://vitejs.dev/guide/static-deploy.html This is also not working for me.
on console: npm run dev

GRaviTy-GAGAN saids:
> Yeah, it's not a simple HTML file right so it won't work with the live server if you are using vite react `npm run dev` if you created the project with NPX create-react-app then `npm start `(depends on what you write inside the script of package.json file)

**Comment by PatrickOjiambo** [comment]
Hello guys, I recently had this issue and this is how I solved it. 
a. Go to settings in your repo. click on pages.
b. Under build and deployment(Branch). Make sure you choose gh-pages as the branch for deployment. I am assuming you have installed gh-pages  using npm.
c. Make sure your packages.json is as follows. I will just write the relevant parts
 "name": "patrickojiambo-github-io",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "homepage": "https://PatrickOjiambo.github.io",
  "scripts": {
    "predeploy": "npm run build",
    "deploy": "gh-pages -d dist",
    "dev": "vite",
    "build": "gh-pages -d dist",
    "lint": "eslint . --ext js,jsx --report-unused-disable-directives --max-warnings 0",
    "preview": "vite preview"

  },
d.Be very keen on the scripts section. 
e. Based on whether you created a repo named "username.github.io" (as I did above) or you have a custom repo. It will affect the "homepage" key above.

**Comment by GinoongFlores** [comment]
### Hello, for those still finding the solution. This is how I able to host my ReactJS repo using custom workflows without needing to install gh-pages in local project dependencies. 

1. Go to your repo settings > actions > general > workflow permissions (and select Read & write permissions)
2. Click Pages > Source (dropdown) > select (GitHub actions) 
3. Create these folders and file of `.github/workflows/deploy.yml` on your root directory 
Paste this code on your `deploy.yml`
```yml
# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload dist repository
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
```
5. add a `base` key on your `vite.config.js`. 
- If you are deploying to `https://<USERNAME>.github.io/`. Alternatively, you can remove base from the configuration, as it defaults to '/'. example: `https://ginoongflores.github.io/`, then don't add a `base` key. 
```js
export default defineConfig({
  plugins: [react()],
  // base: "/ginoongflores.github.io/" don't add this if the your repo is like https://ginoongflores.github.io/
})
```

- If you are deploying to `https://<USERNAME>.github.io/<REPO>/` (eg. your repository is at `https://github.com/<USERNAME>/<REPO>)`, then set base to `'/<REPO>/'`.  Example `https://ginoongflores.github.io/project-1`, then your base key is `base:"/project-1/"`

```js
export default defineConfig({
  plugins: [react()],
  base: "/project-1/" // add this if the your repo is like https://github.com/ginoongflores/project-1)
})
```

7. Commit & Push to GitHub

_Note:_ The `#3` and `#5` is based on vite docs: https://vitejs.dev/guide/static-deploy.html. So, the people who said that they find their solution at that link is right. Always check that docs for any updates. 😃
