### ISSUE TITLE
Problem import css custom files in tailwindcss with react app

### ISSUE THREAD

**Issue by jabed-dev** [facebook/react#25955]
tailwindcss.com provide css file import syntax like down below [Import our provided CSS files](https://tailwindcss.com/docs/using-with-preprocessors#build-time-imports).

```css
@import "tailwindcss/base";
@import "./custom-base-styles.css";

@import "tailwindcss/components";
@import "./custom-components.css";

@import "tailwindcss/utilities";
@import "./custom-utilities.css";
```

I'm using the same way in my react app but it is problem.

```css
@import "tailwindcss/base";
@import "tailwindcss/components";
@import "./my-components.css";
@import "tailwindcss/utilities";
```

## The problem here is my custom style on top of the build.css file.

```css
.my-btn {
  styles ... 
}
/*
! tailwindcss v3.2.4 | MIT License | https://tailwindcss.com
*/*,:after,:before{border:0 solid #e5e7eb;box-sizing:border-box} ....
/*# sourceMappingURL=main.f601fced.css.map*/
```

```json
"react": "^18.2.0",
"tailwindcss": "^3.2.4"
```

Gitgub [repository](https://github.com/jabed-dev/my-react-app)
