### ISSUE TITLE
React can mount with <div placeholder=x> but does not update placeholder attribute

### ISSUE THREAD

**Issue by slorber** [facebook/react#3799]
Hi,

I don't really know if this is expected but the following:

```
var Hello = React.createClass({
    render: function() {
        return <div test={this.props.value} placeholder={this.props.value} data-placeholder={this.props.value}>Hello</div>;
    }
});
 
React.render(<Hello value="World"/>, document.body);
```

Will lead to 

```
<div placeholder="World" data-placeholder="World" data-reactid=".0">Hello</div>
```

It seems that React did not mount the "test" attribute because it's not standart. But actually it mounted the placeholder attribute while it is not standart too. Is this expected?

So React can mount a div with a placeholder attribute in its current state, but the weird thing is that it can't update this attribute.

```
var Hello = React.createClass({
    render: function() {
        return <div test={this.props.value} placeholder={this.props.value} data-placeholder={this.props.value}>Hello</div>;
    }
});
 
React.render(<Hello value="World"/>, document.body);
React.render(<Hello value="WorldUpdated"/>, document.body);
```

This will produce:

```
<div placeholder="World" data-placeholder="WorldUpdated" data-reactid=".0">Hello</div>
```

See http://jsfiddle.net/kb3gN/10968/

Don't know how this is supposed to work but I think the current behavior is kind of unexpected ;)

**Comment by cody** [comment]
That is weird. But it looks like React is innocent. The browser does not update the attribute. On a `<div>` a `placeholder` has no meaning anyway, does it? It works if you change the `<div>` to an `<input>`.

**Comment by slorber** [comment]
I used this property for contenteditable elements to create a placeholder with CSS:

```less
.withDefaultUncontrolledContentEditablePlaceholder() {
  // Apply to self, or childs
  [contenteditable][data-placeholder]:empty:not(:focus):before,
  &[contenteditable][data-placeholder]:empty:not(:focus):before {
    content: attr(data-placeholder);
    color: @colorPlaceholder;
  }

  // Hack for firefox when contentEditable is focused but empty it has a smaller height than it should have
  // See http://stackoverflow.com/questions/23530231/contenteditable-true-height-issue-in-firefox
  [contenteditable]:empty:focus:before,
  &[contenteditable]:empty:focus:before {
    content: '\feff ';
  }
}
```

I have switched to `data-placeholder` instead it works better :)
