### ISSUE TITLE
How to handle would-be duplicate keys in inline styles?

### ISSUE THREAD

**Issue by mkscrg** [facebook/react#3887]
Inline styles are awesome. But for ~~better or~~ worse, some CSS properties have vendor-prefixed values. How can we write these inline in React?

`display: flex` is the example I ran into:

```css
.my-container {
  display: flex;
  display: -webkit-flex;
  /* etc */
}
```

I found myself building something like

```js
render: function() {
  var style = {
    display: "flex",
    display: "-webkit-flex"
  };
  return <div style={style}>/*...*/</div>
};
```

only to be reminded by the linter that it won't work.

What to do in these situations?
