### ISSUE TITLE
CSS Animation example

### ISSUE THREAD

**Issue by ccorcos** [facebook/react#4385]
Hey there, I've been struggling with an animation issue for almost an hour now:

```css
.pop-enter {
  transform: translateX(-33%)
  transition: transform .5s ease-in;
}

.pop-enter.pop-enter-active {
  transform: translateX(0%)
}
```

I'm not expert in CSS animations so I simply copied it from the docs:

https://facebook.github.io/react/docs/animation.html

It turns out, that the solution was this:

```css
.pop-enter {
  transform: translateX(-33%)
}

.pop-enter.pop-enter-active {
  transform: translateX(0%)
  transition: transform .5s ease-in;
}
```

When the element is rendered, it isnt initially set to `transform: translateX(-33%)`. Thus, it tried to animate it. Then the `-active` tag hits and its going back to the same place. Thus it appears as if no animation occurred at all.

You will save someone like a lot of pain and frustration if you fixed this example in the docs :+1:
