### ISSUE TITLE
inline styles rules overriding

### ISSUE THREAD

**Issue by dmatteo** [facebook/react#4399]
We always had to deal with browser inconsistency, and we still have if we want to use inline styling.

It's all nice and good if the property has a different name (prefix), like

```javascript
let style = {
  msFlexDirection: 'row',
  flexDirection: 'row'
}
```

But how to deal with situation when we used to override the rule in CSS?
E.g.
```css
.some-element {
  display: -ms-flexbox
  display: flex
}
```
